-- MySQL Script generated by MySQL Workbench
-- 11/15/16 16:44:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lareleve
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lareleve` ;

-- -----------------------------------------------------
-- Schema lareleve
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lareleve` DEFAULT CHARACTER SET utf8 ;
USE `lareleve` ;

-- -----------------------------------------------------
-- Table `lareleve`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Roles` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Roles` (
  `id` INT NOT NULL,
  `libellé` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `libellé_UNIQUE` (`libellé` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Poles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Poles` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Poles` (
  `id` INT NOT NULL,
  `chefPole` INT NOT NULL,
  `libellé` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`id`),
  INDEX `fk_Poles_Utilisateurs_chef_idx` (`chefPole` ASC),
  UNIQUE INDEX `libellé_UNIQUE` (`libellé` ASC),
  CONSTRAINT `fk_Poles_Utilisateurs_chef`
    FOREIGN KEY (`chefPole`)
    REFERENCES `lareleve`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Services` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Services` (
  `id` INT NOT NULL,
  `idPole` INT NOT NULL,
  `libellé` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Services_Poles_id_idx` (`idPole` ASC),
  UNIQUE INDEX `libellé_UNIQUE` (`libellé` ASC),
  CONSTRAINT `fk_Services_Poles_id`
    FOREIGN KEY (`idPole`)
    REFERENCES `lareleve`.`Poles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Utilisateurs` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Utilisateurs` (
  `id` INT NOT NULL,
  `idService` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Utilisateurs_Services_id_idx` (`idService` ASC),
  CONSTRAINT `fk_Utilisateurs_Services_id`
    FOREIGN KEY (`idService`)
    REFERENCES `lareleve`.`Services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`RolesUtilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`RolesUtilisateurs` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`RolesUtilisateurs` (
  `idRole` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idRole`, `idUtilisateur`),
  INDEX `fk_RolesUtilisateurs_Utilisateurs_id_idx` (`idUtilisateur` ASC),
  CONSTRAINT `fk_RolesUtilisateurs_Roles_id`
    FOREIGN KEY (`idRole`)
    REFERENCES `lareleve`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RolesUtilisateurs_Utilisateurs_id`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `lareleve`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Logements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Logements` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Logements` (
  `id` INT NOT NULL,
  `idPOHI` INT NULL,
  `idGestimmLogement` INT NULL,
  `idGestimmMenages` INT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `etage` INT NULL,
  `digicode` VARCHAR(45) NULL,
  `direction` VARCHAR(255) NULL,
  `type` VARCHAR(45) NULL,
  `superficie` INT NULL,
  `loyer` INT NULL,
  `charges` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Menages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Menages` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Menages` (
  `id` INT NOT NULL,
  `idReferant` INT NULL,
  `idLogement` INT NULL,
  `dateEntree` DATETIME NULL,
  `dateSortie` DATETIME NULL,
  `adresseSortie` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Menages_Utilisateurs_referant_idx` (`idReferant` ASC),
  INDEX `fk_Menages_Logements1_idx` (`idLogement` ASC),
  CONSTRAINT `fk_Menages_Utilisateurs_referant`
    FOREIGN KEY (`idReferant`)
    REFERENCES `lareleve`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menages_Logements1`
    FOREIGN KEY (`idLogement`)
    REFERENCES `lareleve`.`Logements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Besoins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Besoins` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Besoins` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `libellé_UNIQUE` (`libelle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Actes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Actes` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Actes` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `libellé_UNIQUE` (`libelle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Prestations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Prestations` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Prestations` (
  `id` INT NOT NULL,
  `idBesoin` INT NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Prestations_Besoins_id_idx` (`idBesoin` ASC),
  UNIQUE INDEX `libellé_UNIQUE` (`libelle` ASC),
  CONSTRAINT `fk_Prestations_Besoins_id`
    FOREIGN KEY (`idBesoin`)
    REFERENCES `lareleve`.`Besoins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Individus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Individus` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Individus` (
  `id` INT NOT NULL,
  `idMenage` INT NOT NULL,
  `nomNaissance` VARCHAR(45) NOT NULL,
  `nomUsage` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `tel` INT NULL,
  `villeNaissance` VARCHAR(45) NULL,
  `statutMatrimonial` VARCHAR(45) NULL,
  `dateEntreeFr` DATETIME NULL,
  `statutFr` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Individus_Menages_id_idx` (`idMenage` ASC),
  CONSTRAINT `fk_Individus_Menages_id`
    FOREIGN KEY (`idMenage`)
    REFERENCES `lareleve`.`Menages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`PrestationsRealisees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`PrestationsRealisees` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`PrestationsRealisees` (
  `id` INT NOT NULL,
  `idPrestation` INT NOT NULL,
  `seqPrestation` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  `idMenage` INT NULL,
  `idIndividu` INT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `dateCreation` DATETIME NOT NULL,
  `dateFin` DATETIME NULL,
  `commentaire` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PrestationsRealisees_Prestations_id_idx` (`idPrestation` ASC),
  INDEX `fk_PrestationsRealisees_Menages_id_idx` (`idMenage` ASC),
  INDEX `fk_PrestationsRealisees_Individu_id_idx` (`idIndividu` ASC),
  INDEX `fk_PrestationsRealisees_Utilisateur_id_idx` (`idUtilisateur` ASC),
  CONSTRAINT `fk_PrestationsRealisees_Prestations_id`
    FOREIGN KEY (`idPrestation`)
    REFERENCES `lareleve`.`Prestations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrestationsRealisees_Menages_id`
    FOREIGN KEY (`idMenage`)
    REFERENCES `lareleve`.`Menages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrestationsRealisees_Individu_id`
    FOREIGN KEY (`idIndividu`)
    REFERENCES `lareleve`.`Individus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PrestationsRealisees_Utilisateur_id`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `lareleve`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`ActesRealises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`ActesRealises` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`ActesRealises` (
  `id` INT NOT NULL,
  `idActe` INT NOT NULL,
  `seqActe` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  `idMenage` INT NULL,
  `idIndividu` INT NULL,
  `idBesoin` INT NULL,
  `idPrestationRealisee` INT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `dateRealisation` DATETIME NOT NULL,
  `commentaire` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ActesRealisees_Actes_id_idx` (`idActe` ASC),
  INDEX `fk_ActesRealisees_Individu_id_idx` (`idIndividu` ASC),
  INDEX `fk_ActesRealisees_Menages_id_idx` (`idMenage` ASC),
  INDEX `fk_ActesRealisees_Besoins_id_idx` (`idBesoin` ASC),
  INDEX `fk_ActesRealisees_PrestationsRealises_id_idx` (`idPrestationRealisee` ASC),
  INDEX `fk_ActesRealisees_Utilisateurs_id_idx` (`idUtilisateur` ASC),
  CONSTRAINT `fk_ActesRealisees_Actes_id`
    FOREIGN KEY (`idActe`)
    REFERENCES `lareleve`.`Actes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActesRealisees_Menages_id`
    FOREIGN KEY (`idMenage`)
    REFERENCES `lareleve`.`Menages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActesRealisees_Individus_id`
    FOREIGN KEY (`idIndividu`)
    REFERENCES `lareleve`.`Individus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActesRealisees_Besoins_id`
    FOREIGN KEY (`idBesoin`)
    REFERENCES `lareleve`.`Besoins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActesRealisees_PrestationsRealises_id`
    FOREIGN KEY (`idPrestationRealisee`)
    REFERENCES `lareleve`.`PrestationsRealisees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActesRealisees_Utilisateurs_id`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `lareleve`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Langues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Langues` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Langues` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `libellé_UNIQUE` (`libelle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Collocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Collocation` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Collocation` (
  `idGestimm` INT NOT NULL,
  `idLogement` INT NULL,
  `dateEntree` DATETIME NULL,
  PRIMARY KEY (`idGestimm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Ressources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Ressources` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Ressources` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `libelle_UNIQUE` (`libelle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Langues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Langues` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Langues` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `libellé_UNIQUE` (`libelle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`RessourcesIndividus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`RessourcesIndividus` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`RessourcesIndividus` (
  `idIndividu` INT NOT NULL,
  `idRessources` VARCHAR(45) NOT NULL,
  `montantRessource` INT NULL,
  PRIMARY KEY (`idIndividu`, `idRessources`),
  INDEX `fk_Individus_has_Ressources_Ressources1_idx` (`idRessources` ASC),
  INDEX `fk_Individus_has_Ressources_Individus1_idx` (`idIndividu` ASC),
  CONSTRAINT `fk_Individus_has_Ressources_Individus1`
    FOREIGN KEY (`idIndividu`)
    REFERENCES `lareleve`.`Individus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Individus_has_Ressources_Ressources1`
    FOREIGN KEY (`idRessources`)
    REFERENCES `lareleve`.`Ressources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`RessourcesMenages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`RessourcesMenages` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`RessourcesMenages` (
  `idMenage` INT NOT NULL,
  `idRessources` VARCHAR(45) NOT NULL,
  `montantRessource` INT NULL,
  PRIMARY KEY (`idMenage`, `idRessources`),
  INDEX `fk_Menages_has_Ressources_Ressources1_idx` (`idRessources` ASC),
  INDEX `fk_Menages_has_Ressources_Menages1_idx` (`idMenage` ASC),
  CONSTRAINT `fk_Menages_has_Ressources_Menages1`
    FOREIGN KEY (`idMenage`)
    REFERENCES `lareleve`.`Menages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menages_has_Ressources_Ressources1`
    FOREIGN KEY (`idRessources`)
    REFERENCES `lareleve`.`Ressources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`LanguesIndividus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`LanguesIndividus` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`LanguesIndividus` (
  `idIndividu` INT NOT NULL,
  `idLangue` VARCHAR(45) NOT NULL,
  `niveauLangue` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIndividu`, `idLangue`),
  INDEX `fk_Individus_has_Langue_Langue1_idx` (`idLangue` ASC),
  INDEX `fk_Individus_has_Langue_Individus1_idx` (`idIndividu` ASC),
  CONSTRAINT `fk_Individus_has_Langue_Individus1`
    FOREIGN KEY (`idIndividu`)
    REFERENCES `lareleve`.`Individus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Individus_has_Langue_Langue1`
    FOREIGN KEY (`idLangue`)
    REFERENCES `lareleve`.`Langues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`Nationnalites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`Nationnalites` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`Nationnalites` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `libellé_UNIQUE` (`libelle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lareleve`.`NationnalitesIndividus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lareleve`.`NationnalitesIndividus` ;

CREATE TABLE IF NOT EXISTS `lareleve`.`NationnalitesIndividus` (
  `idIndividu` INT NOT NULL,
  `idNationnalite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIndividu`, `idNationnalite`),
  INDEX `fk_Individus_has_Nationnalites_Nationnalites1_idx` (`idNationnalite` ASC),
  INDEX `fk_Individus_has_Nationnalites_Individus1_idx` (`idIndividu` ASC),
  CONSTRAINT `fk_Individus_has_Nationnalites_Individus1`
    FOREIGN KEY (`idIndividu`)
    REFERENCES `lareleve`.`Individus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Individus_has_Nationnalites_Nationnalites1`
    FOREIGN KEY (`idNationnalite`)
    REFERENCES `lareleve`.`Nationnalites` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `lareleve`;

DELIMITER $$

USE `lareleve`$$
DROP TRIGGER IF EXISTS `lareleve`.`Logements_AFTER_UPDATE` $$
USE `lareleve`$$
CREATE DEFINER = CURRENT_USER TRIGGER `lareleve`.`Logements_AFTER_UPDATE` AFTER UPDATE ON `Logements` 
FOR EACH ROW
BEGIN
	IF NEW.statut = "passif" THEN
		SET count = (SELECT COUNT(*) FROM `Menages` WHERE idLogement = NEW.id);
        IF count > 0 THEN
			SIGNAL SQLSTATE '45000' set message_text = 'Erreur : Logement affecté à un ménage';
        END IF;
		
    END IF;
END$$


USE `lareleve`$$
DROP TRIGGER IF EXISTS `lareleve`.`Menages_BEFORE_INSERT` $$
USE `lareleve`$$
CREATE DEFINER = CURRENT_USER TRIGGER `lareleve`.`Menages_BEFORE_INSERT` BEFORE INSERT ON `Menages` 
FOR EACH ROW
BEGIN
	IF NEW.dateSortie != null AND NEW.dateEntree > dateSortie THEN
		SIGNAL SQLSTATE '45000' set message_text = 'Erreur : dateEntree > dateSortie';
    END IF;
END$$


USE `lareleve`$$
DROP TRIGGER IF EXISTS `lareleve`.`Menages_BEFORE_UPDATE` $$
USE `lareleve`$$
CREATE DEFINER = CURRENT_USER TRIGGER `lareleve`.`Menages_BEFORE_UPDATE` BEFORE UPDATE ON `Menages` 
FOR EACH ROW
BEGIN
	IF NEW.dateSortie != null AND NEW.dateEntree > dateSortie THEN
		SIGNAL SQLSTATE '45000' set message_text = 'Erreur : dateEntree > dateSortie';
    END IF;
END$$


USE `lareleve`$$
DROP TRIGGER IF EXISTS `lareleve`.`PrestationsRealisees_BEFORE_UPDATE` $$
USE `lareleve`$$
CREATE DEFINER = CURRENT_USER TRIGGER `lareleve`.`PrestationsRealisees_BEFORE_UPDATE` BEFORE UPDATE ON `PrestationsRealisees` FOR EACH ROW
BEGIN
	IF NEW.idMenage != 0 THEN
		SET NEW.idMenage = 0;
    END IF;
END
$$


USE `lareleve`$$
DROP TRIGGER IF EXISTS `lareleve`.`RessourcesIndividus_BEFORE_INSERT` $$
USE `lareleve`$$
CREATE DEFINER = CURRENT_USER TRIGGER `lareleve`.`RessourcesIndividus_BEFORE_INSERT` BEFORE INSERT ON `RessourcesIndividus`
 FOR EACH ROW
BEGIN
    SET count = (SELECT COUNT(*) FROM `Ressources` WHERE id = NEW.idRessources AND type = "individu");
    
    IF count = 0 THEN
		SIGNAL SQLSTATE '45000' set message_text = "Erreur : la ressource n'est pas une ressource d'individu";
    END IF;
END$$


USE `lareleve`$$
DROP TRIGGER IF EXISTS `lareleve`.`RessourcesIndividus_BEFORE_UPDATE` $$
USE `lareleve`$$
CREATE DEFINER = CURRENT_USER TRIGGER `lareleve`.`RessourcesIndividus_BEFORE_UPDATE` BEFORE UPDATE ON `RessourcesIndividus` 
FOR EACH ROW
BEGIN
    SET count = (SELECT COUNT(*) FROM `Ressources` WHERE id = NEW.idRessources AND type = "individu");
    
    IF count = 0 THEN
		SIGNAL SQLSTATE '45000' set message_text = "Erreur : la ressource n'est pas une ressource d'individu";
    END IF;
END$$


USE `lareleve`$$
DROP TRIGGER IF EXISTS `lareleve`.`RessourcesMenages_BEFORE_INSERT` $$
USE `lareleve`$$
CREATE DEFINER = CURRENT_USER TRIGGER `lareleve`.`RessourcesMenages_BEFORE_INSERT` BEFORE INSERT ON `RessourcesMenages` 
FOR EACH ROW
BEGIN
    SET count = (SELECT COUNT(*) FROM `Ressources` WHERE id = NEW.idRessources AND type = "menage");
    
    IF count = 0 THEN
		SIGNAL SQLSTATE '45000' set message_text = "Erreur : la ressource n'est pas une ressource de ménage";
    END IF;
END$$


USE `lareleve`$$
DROP TRIGGER IF EXISTS `lareleve`.`RessourcesMenages_BEFORE_UPDATE` $$
USE `lareleve`$$
CREATE DEFINER = CURRENT_USER TRIGGER `lareleve`.`RessourcesMenages_BEFORE_UPDATE` BEFORE UPDATE ON `RessourcesMenages` FOR EACH ROW
BEGIN
    SET count = (SELECT COUNT(*) FROM `Ressources` WHERE id = NEW.idRessources AND type = "menage");
    
    IF count = 0 THEN
		SIGNAL SQLSTATE '45000' set message_text = "Erreur : la ressource n'est pas une ressource de ménage";
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
