-- MySQL Script generated by MySQL Workbench
-- Tue Nov  1 15:19:37 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lareleve
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lareleve` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lareleve` ;

-- -----------------------------------------------------
-- Table `lareleve`.`Utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lareleve`.`Utilisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
  ) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- TEMPORARY --
INSERT INTO Utilisateurs (id, password, username, nom, prenom) VALUES (1, 'pass1', 'gattazr', 'GATTAZ', 'Remi'), (2, 'pass2', 'dunanq', 'DUNAND', 'Quentin');
